### ISSUE TITLE
Additional information in notifications

### ISSUE THREAD

**Issue by justmytwospence** [colonelpanic8/mu4e-notifications#1]
As per a suggestion in the mailing list, it would be interesting to consider how additional information could be presented in notification messages, eg subject, from, etc.

**Comment by colonelpanic8** [comment]
What mailing list? are you looking for mu4e alert?

**Comment by justmytwospence** [comment]
Woops a daisy that's indeed where I thought I was

**Comment by colonelpanic8** [comment]
@justmytwospence just noticed you work at Uber. Do you use mu4e for work email?
